src/Entity/Profil.php
<?php

namespace App\Entity;

use App\Repository\ProfilRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProfilRepository::class)]
class Profil
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $formation = null;

    #[ORM\Column(nullable: true)]
    private ?int $annee_formation = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFormation(): ?string
    {
        return $this->formation;
    }

    public function setFormation(?string $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    public function getAnneeFormation(): ?int
    {
        return $this->annee_formation;
    }

    public function setAnneeFormation(?int $annee_formation): self
    {
        $this->annee_formation = $annee_formation;

        return $this;
    }
}

src/Form/ProfilType.php
<?php

namespace App\Form;

use App\Entity\Profil;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('email')
            ->add('formation')
            ->add('annee_formation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Profil::class,
        ]);
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Profil;
use App\Form\ProfilType;
use App\Repository\ProfilRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/profil')]
class ProfilController extends AbstractController
{
    #[Route('/', name: 'app_profil_index', methods: ['GET'])]
    public function index(ProfilRepository $profilRepository): Response
    {
        return $this->render('profil/index.html.twig', [
            'profils' => $profilRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_profil_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProfilRepository $profilRepository): Response
    {
        $profil = new Profil();
        $form = $this->createForm(ProfilType::class, $profil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $profilRepository->save($profil, true);

            return $this->redirectToRoute('app_profil_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('profil/new.html.twig', [
            'profil' => $profil,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_profil_show', methods: ['GET'])]
    public function show(Request $request, ProfilRepository $profilRepository, Profil $profil): Response
   
        
  {
           return $this->render('profil/show.html.twig', ['id' => $profil->getId(),
        'profil'=>$profil]);
        ;
                 
    }

    

    #[Route('/{id}/edit', name: 'app_profil_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Profil $profil): Response
    {
        $form = $this->createForm(ProfilType::class, $profil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $profilRepository->save($profil, true);

            return $this->redirectToRoute('app_profil_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('profil/edit.html.twig', [
            'profil' => $profil,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_profil_delete', methods: ['POST'])]
    public function delete(Request $request, Profil $profil, ProfilRepository $profilRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$profil->getId(), $request->request->get('_token'))) {
            $profilRepository->remove($profil, true);
        }

        return $this->redirectToRoute('app_profil_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/profil/_delete_form.html.twig
<form method="post" action="{{ path('app_profil_delete', {'id': profil.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ profil.id) }}">
    <button class="btn">Delete</button>
</form>

templates/profil/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/profil/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Profil{% endblock %}

{% block body %}
    <h1>Edit Profil</h1>

    {{ include('profil/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_profil_index') }}">back to list</a>

    {{ include('profil/_delete_form.html.twig') }}
{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil index{% endblock %}

{% block body %}
    <h1>Profil index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Email</th>
                <th>Formation</th>
                <th>Annee_formation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for profil in profils %}
            <tr>
                <td>{{ profil.id }}</td>
                <td>{{ profil.nom }}</td>
                <td>{{ profil.prenom }}</td>
                <td>{{ profil.email }}</td>
                <td>{{ profil.formation }}</td>
                <td>{{ profil.anneeFormation }}</td>
                <td>
                    <a href="{{ path('app_profil_show', {'id': profil.id}) }}">show</a>
                    <a href="{{ path('app_profil_edit', {'id': profil.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_profil_new') }}">Create new</a>
{% endblock %}

templates/profil/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Profil{% endblock %}

{% block body %}
    <h1>Create new Profil</h1>

    {{ include('profil/_form.html.twig') }}

    <a href="{{ path('app_profil_index') }}">back to list</a>
{% endblock %}

templates/profil/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}
    <h1>Profil</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ profil.nom}}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ profil.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ profil.email }}</td>
            </tr>
            <tr>
                <th>Formation</th>
                <td>{{ profil.formation }}</td>
            </tr>
            <tr>
                <th>Annee_formation</th>
                <td>{{ profil.anneeFormation }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_profil_index') }}">back to list</a>

    <a href="{{ path('app_profil_edit', {'id': profil.id}) }}">edit</a>

    {{ include('profil/_delete_form.html.twig') }}
{% endblock %}